# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 09:35
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='General',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_w', models.IntegerField(default=0)),
                ('count_s', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=13)),
                ('timesShown', models.IntegerField(default=0)),
                ('timesCorrected', models.IntegerField(default=0)),
                ('succesRatio', models.DecimalField(decimal_places=4, default=Decimal('0.5'), max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='sample',
            name='root',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spotter.Word'),
        ),
    ]
