# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotter', '0002_auto_20170210_1014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='id',
        ),
        migrations.AddField(
            model_name='word',
            name='idd',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
